### ISSUE TITLE
my first issue

### ISSUE THREAD

**Issue by AiyionPrime** [gr4yj3d1/toolshed#1]
Muss das so?

```console
(venv) aiyion@chromia:~/Documents/j3d1/toolshed/backend$ python manage.py migrate 
System check identified some issues:

WARNINGS:
?: (staticfiles.W004) The directory '/home/aiyion/Documents/j3d1/toolshed/backend/static' in the STATICFILES_DIRS setting does not exist.
Traceback (most recent call last):
  File "/home/aiyion/Documents/j3d1/toolshed/backend/venv/lib/python3.11/site-packages/django/db/migrations/loader.py", line 187, in check_key
    return self.graph.root_nodes(key[0])[0]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aiyion/Documents/j3d1/toolshed/backend/manage.py", line 22, in <module>
    main()
  File "/home/aiyion/Documents/j3d1/toolshed/backend/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/aiyion/Documents/j3d1/toolshed/backend/venv/lib/python3.11/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/home/aiyion/Documents/j3d1/toolshed/backend/venv/lib/python3.11/site-packages/django/core/management/__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/aiyion/Documents/j3d1/toolshed/backend/venv/lib/python3.11/site-packages/django/core/management/base.py", line 402, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/aiyion/Documents/j3d1/toolshed/backend/venv/lib/python3.11/site-packages/django/core/management/base.py", line 448, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aiyion/Documents/j3d1/toolshed/backend/venv/lib/python3.11/site-packages/django/core/management/base.py", line 96, in wrapped
    res = handle_func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aiyion/Documents/j3d1/toolshed/backend/venv/lib/python3.11/site-packages/django/core/management/commands/migrate.py", line 114, in handle
    executor = MigrationExecutor(connection, self.migration_progress_callback)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aiyion/Documents/j3d1/toolshed/backend/venv/lib/python3.11/site-packages/django/db/migrations/executor.py", line 18, in __init__
    self.loader = MigrationLoader(self.connection)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aiyion/Documents/j3d1/toolshed/backend/venv/lib/python3.11/site-packages/django/db/migrations/loader.py", line 58, in __init__
    self.build_graph()
  File "/home/aiyion/Documents/j3d1/toolshed/backend/venv/lib/python3.11/site-packages/django/db/migrations/loader.py", line 250, in build_graph
    self.add_external_dependencies(key, migration)
  File "/home/aiyion/Documents/j3d1/toolshed/backend/venv/lib/python3.11/site-packages/django/db/migrations/loader.py", line 214, in add_external_dependencies
    parent = self.check_key(parent, key[0])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aiyion/Documents/j3d1/toolshed/backend/venv/lib/python3.11/site-packages/django/db/migrations/loader.py", line 194, in check_key
    raise ValueError(
ValueError: Dependency on app with no migrations: authentication
```

**Comment by Kamaruddheen** [comment]
Hi @AiyionPrime 

I have noted two issue from your project,

1. No static folder is present in root/backend folder
2. Before running migrate, I hope you have ran makemiragrations command if not do run it first.
